### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by jasper-k** [dstreev/hadoop-cli#7]
Hi,
I found that whenever you are in the basefolder of the hadoop-cli the classpath setting doesn't work and there is an error "com.streever.hadoop.HadoopShell"

To reproduce: 
======================================
[sandbox@bd-sandbox tmp]$ cd /tmp/hadoop-cli-3.1/
[sandbox@bd-sandbox hadoop-cli-3.1]$ ls -la
total 47252
drwxrwxr-x    2 sandbox sandbox       86 Aug 29 14:43 .
drwxrwxrwt. 110 root    root       12288 Aug 29 14:47 ..
-rwxr-xr-x    1 sandbox sandbox     1792 Jul  9 15:16 hadoopcli
-rw-r--r--    1 sandbox sandbox 48355526 Aug 10 01:54 hadoop-cli-full-bin.jar
-rwxr-xr-x    1 sandbox sandbox      831 Jun  4 22:24 JCECheck
-rwxr-xr-x    1 sandbox sandbox      776 Jun  4 22:24 setup.sh
[sandbox@bd-sandbox hadoop-cli-3.1]$
[sandbox@bd-sandbox hadoop-cli-3.1]$ hadoopcli
**Error: Could not find or load main class com.streever.hadoop.HadoopShell**

**Comment by dstreev** [comment]
Release as Beta for Testing/Validation: https://github.com/dstreev/hadoop-cli/releases/tag/ISSUE_7-8

Will require an installation via './setup.sh' to correct existing startup scripts.

In this case, you were trying to launch binaries from the 'install' directory with the previously installed 'hadoopcli' script which is in the path.  Warning message added with instructions.
